spring:
  datasource:
    url: jdbc:mysql://121.36.77.21:3306/dfq?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 30000
      validation-timeout: 250
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

#  thymeleaf:
##    关闭缓存
#    cache: false
#    servlet:
#      content-type: text/html
#    enabled: true
#    encoding: UTF-8
#    mode: LEGACYHTML5
##    配置路由字符串拼接
#    prefix: classpath:/templates/
#    suffix: .html

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 80


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
